cursor #dde3ee
cursor_text_color #c1c7d2

foreground            #dde3ee
background            #0e141c
selection_foreground  #24304d
selection_background  #bbc6ea
url_color             #a0c9ff

color0   #0e141c
color1   #ff729b
color2   #7fff91
color3   #fff772
color4   #85b4f2
color5   #254876
color6   #a0c9ff
color7   #eff6ff
color8   #999ea5
color9   #ff9fbb
color10  #a5ffb2
color11  #fffaa5
color12  #aed1ff
color13  #bcd9ff
color14  #d4e6ff
color15  #f8fbff
