cursor #e3e1ef
cursor_text_color #c7c5d3

foreground            #e3e1ef
background            #12121c
selection_foreground  #342b4b
selection_background  #cdc0e9
url_color             #c0c1ff

color0   #12121c
color1   #ff7294
color2   #7fff96
color3   #ffd872
color4   #aaabf2
color5   #404176
color6   #c0c1ff
color7   #efefff
color8   #9999a5
color9   #ff9fb6
color10  #a5ffb5
color11  #ffe6a5
color12  #c9caff
color13  #d2d3ff
color14  #e2e3ff
color15  #f8f8ff
